extract = 'total_dyn_inst: (\d+)'
benchmarks = 'bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brilirs -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "python3 optimization.py brench",
    "brilirs -p {args}",
]