extract = 'total_dyn_inst: (\d+)'
benchmarks = '/Users/collin/Documents/Projects/bril/benchmarks/*/*.bril'

[runs.baseline]
pipeline = [
    "/Users/collin/Library/Python/3.11/bin/bril2json",
    "brilirs -p {args}",
]

[runs.myopt]
pipeline = [
    "/Users/collin/Library/Python/3.11/bin/bril2json",
    "python3 /Users/collin/Documents/Projects/cs6120tasks/task6/task6.py",
    "RUST_BACKTRACE=full brilirs -p {args}",
]